on:
  push:

jobs:
  code-formatter:
    name: "code formatter"
    uses: jcergolj/reusable-github-actions/.github/workflows/code-formatter.yml@master
    with:
      skip-npm: true

  larastan:
    name: "larastan"
    uses: jcergolj/reusable-github-actions/.github/workflows/larastan.yml@master

  envy:
    name: "envy"
    uses: jcergolj/reusable-github-actions/.github/workflows/envy.yml@master

  tests:
    name: "tests"
    uses: jcergolj/reusable-github-actions/.github/workflows/tests.yml@master
    with:
      install-tailwind-css: true

  gitleaks:
    name: "gitleaks scan"
    uses: jcergolj/reusable-github-actions/.github/workflows/gitleaks.yml@master

  trufflehog-scan:
    name: "trufflehog scan"
    uses: jcergolj/reusable-github-actions/.github/workflows/trufflehog-scan.yml@master
