on:
  push:

jobs:
  code-formatter:
    name: "code formatter"
    uses: jcergolj/reusable-github-actions/.github/workflows/code-formatter.yml@v3
    with:
      pint-blade: true
      skip-npm: true

  larastan:
    name: "larastan"
    uses: jcergolj/reusable-github-actions/.github/workflows/larastan.yml@v3

  envy:
    name: "envy"
    uses: jcergolj/reusable-github-actions/.github/workflows/envy.yml@v3

  tests:
    name: "tests"
    uses: jcergolj/reusable-github-actions/.github/workflows/tests.yml@v3
    with:
      install-tailwind-css: true

  gitleaks:
    name: "gitleaks scan"
    uses: jcergolj/reusable-github-actions/.github/workflows/gitleaks.yml@v3

  trufflehog-scan:
    name: "trufflehog scan"
    uses: jcergolj/reusable-github-actions/.github/workflows/trufflehog-scan.yml@v3

  deploy:
    if: github.ref == 'refs/heads/master'
    name: "deploy"
    needs:
      - code-formatter
      - larastan
      - envy
      - tests
      - gitleaks
      - trufflehog-scan
    uses: jcergolj/reusable-github-actions/.github/workflows/deploy-only.yml@v3
    secrets: inherit
